package com.forkbombsquad.stillalivelarp.mockdata

class MockData {
    companion object {

        const val GET_ALL_PLAYERS_RESPONSE = """
            {
              "players": [
                {
                  "experience": "2",
                  "freeTier1Skills": "0",
                  "fullName": "Rydge Craker",
                  "id": 1,
                  "isAdmin": "TRUE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2018/06/02",
                  "numEventsAttended": "6",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "0",
                  "startDate": "2017/04/30",
                  "username": "rydgecraker@gmail.com"
                },
                {
                  "experience": "20",
                  "freeTier1Skills": "0",
                  "fullName": "Brianna Craker",
                  "id": 2,
                  "isAdmin": "TRUE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2018/06/02",
                  "numEventsAttended": "6",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "1",
                  "startDate": "2017/05/22",
                  "username": "brimail96@gmail.com"
                },
                {
                  "experience": "41",
                  "freeTier1Skills": "0",
                  "fullName": "Kevin Novy",
                  "id": 3,
                  "isAdmin": "TRUE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2018/06/02",
                  "numEventsAttended": "6",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "1",
                  "startDate": "2017/05/22",
                  "username": "kevinnovy@yahoo.com"
                },
                {
                  "experience": "0",
                  "freeTier1Skills": "0",
                  "fullName": "Google Test",
                  "id": 4,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "",
                  "numEventsAttended": "0",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "1",
                  "startDate": "2023/05/25",
                  "username": "googletestaccount@gmail.com"
                },
                {
                  "experience": "89",
                  "freeTier1Skills": "0",
                  "fullName": "Ethan Novy",
                  "id": 5,
                  "isAdmin": "TRUE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2018/06/02",
                  "numEventsAttended": "6",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "1",
                  "startDate": "2017/05/01",
                  "username": "ethannovy@yahoo.com"
                },
                {
                  "experience": "3",
                  "freeTier1Skills": "0",
                  "fullName": "Sarah Englert",
                  "id": 6,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "7",
                  "numNpcEventsAttended": "7",
                  "prestigePoints": "0",
                  "startDate": "2023/06/03",
                  "username": "srhartzell524@gmail.com"
                },
                {
                  "experience": "2",
                  "freeTier1Skills": "0",
                  "fullName": "Jeffrey Englert",
                  "id": 7,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/25",
                  "numEventsAttended": "7",
                  "numNpcEventsAttended": "7",
                  "prestigePoints": "0",
                  "startDate": "2023/06/03",
                  "username": "jeffrey.e.englert@gmail.com"
                },
                {
                  "experience": "0",
                  "freeTier1Skills": "0",
                  "fullName": "Justin Sandberg",
                  "id": 10,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "",
                  "numEventsAttended": "0",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "0",
                  "startDate": "2023/06/05",
                  "username": "sandbejd@gmail.com"
                },
                {
                  "experience": "1",
                  "freeTier1Skills": "0",
                  "fullName": "Platt Johnson",
                  "id": 11,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "6",
                  "numNpcEventsAttended": "6",
                  "prestigePoints": "0",
                  "startDate": "2023/09/16",
                  "username": "plattj26@gmail.com"
                },
                {
                  "experience": "6",
                  "freeTier1Skills": "1",
                  "fullName": "Luke Friedl ",
                  "id": 12,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "",
                  "numEventsAttended": "0",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "1",
                  "startDate": "2024/03/07",
                  "username": "luke.friedl@yahoo.com"
                },
                {
                  "experience": "0",
                  "freeTier1Skills": "0",
                  "fullName": "Corey Oliphant",
                  "id": 13,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "",
                  "numEventsAttended": "0",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "0",
                  "startDate": "2024/03/14",
                  "username": "coreysather@gmail.com"
                },
                {
                  "experience": "0",
                  "freeTier1Skills": "0",
                  "fullName": "Mark Flyte",
                  "id": 14,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "",
                  "numEventsAttended": "0",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "0",
                  "startDate": "2024/03/27",
                  "username": "m.a.flyte@gmail.com"
                },
                {
                  "experience": "2",
                  "freeTier1Skills": "0",
                  "fullName": "Matthew Timmons",
                  "id": 15,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "7",
                  "numNpcEventsAttended": "7",
                  "prestigePoints": "1",
                  "startDate": "2024/03/28",
                  "username": "artistxhairs@gmail.com"
                },
                {
                  "experience": "-1",
                  "freeTier1Skills": "0",
                  "fullName": "Rylie Lionheart",
                  "id": 16,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "7",
                  "numNpcEventsAttended": "7",
                  "prestigePoints": "0",
                  "startDate": "2024/03/29",
                  "username": "vixenprincess31@gmail.com"
                },
                {
                  "experience": "4",
                  "freeTier1Skills": "1",
                  "fullName": "Bebe Glesne",
                  "id": 17,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "5",
                  "numNpcEventsAttended": "5",
                  "prestigePoints": "0",
                  "startDate": "2024/04/02",
                  "username": "bebe.glesne@gmail.com"
                },
                {
                  "experience": "1",
                  "freeTier1Skills": "0",
                  "fullName": "Joshua de Block",
                  "id": 18,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2024/08/25",
                  "numEventsAttended": "2",
                  "numNpcEventsAttended": "1",
                  "prestigePoints": "0",
                  "startDate": "2024/04/03",
                  "username": "deblockj0482@gmail.com"
                },
                {
                  "experience": "20",
                  "freeTier1Skills": "3",
                  "fullName": "Kollin Bode",
                  "id": 19,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "6",
                  "numNpcEventsAttended": "6",
                  "prestigePoints": "0",
                  "startDate": "2024/04/06",
                  "username": "scootscott101@gmail.com"
                },
                {
                  "experience": "-1",
                  "freeTier1Skills": "0",
                  "fullName": "Isaac Lytle ",
                  "id": 20,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/06/02",
                  "numEventsAttended": "2",
                  "numNpcEventsAttended": "2",
                  "prestigePoints": "0",
                  "startDate": "2024/04/07",
                  "username": "lytleij26@uww.edu"
                },
                {
                  "experience": "12",
                  "freeTier1Skills": "0",
                  "fullName": "Noah Gudenschwager",
                  "id": 21,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/06/01",
                  "numEventsAttended": "4",
                  "numNpcEventsAttended": "4",
                  "prestigePoints": "1",
                  "startDate": "2024/04/07",
                  "username": "noahgudie@gmail.com"
                },
                {
                  "experience": "3",
                  "freeTier1Skills": "1",
                  "fullName": "DS Schroeder",
                  "id": 22,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "",
                  "numEventsAttended": "0",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "0",
                  "startDate": "2024/04/12",
                  "username": "david.s.schroeder@gmail.com"
                },
                {
                  "experience": "4",
                  "freeTier1Skills": "0",
                  "fullName": "Solomon Stevens",
                  "id": 23,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "4",
                  "numNpcEventsAttended": "4",
                  "prestigePoints": "0",
                  "startDate": "2024/04/22",
                  "username": "sboysteve@gmail.com"
                },
                {
                  "experience": "0",
                  "freeTier1Skills": "0",
                  "fullName": "Jake Korinek",
                  "id": 24,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "",
                  "numEventsAttended": "0",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "0",
                  "startDate": "2024/05/17",
                  "username": "05_duct_sphere@icloud.com"
                },
                {
                  "experience": "4",
                  "freeTier1Skills": "1",
                  "fullName": "Carey Craker",
                  "id": 25,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "",
                  "numEventsAttended": "0",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "0",
                  "startDate": "2024/06/10",
                  "username": "crakercarey@gmail.com"
                },
                {
                  "experience": "2",
                  "freeTier1Skills": "0",
                  "fullName": "Andrew Lindaas",
                  "id": 26,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/06/21",
                  "numEventsAttended": "1",
                  "numNpcEventsAttended": "1",
                  "prestigePoints": "0",
                  "startDate": "2025/03/15",
                  "username": "adlindaas@gmail.com"
                },
                {
                  "experience": "1",
                  "freeTier1Skills": "0",
                  "fullName": "Marisa Considine",
                  "id": 27,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "2",
                  "numNpcEventsAttended": "2",
                  "prestigePoints": "0",
                  "startDate": "2025/05/26",
                  "username": "considinemarisa@gmail.com"
                },
                {
                  "experience": "3",
                  "freeTier1Skills": "0",
                  "fullName": "Jared Levine",
                  "id": 28,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "2",
                  "numNpcEventsAttended": "2",
                  "prestigePoints": "0",
                  "startDate": "2025/05/26",
                  "username": "caelcyndar@gmail.com"
                },
                {
                  "experience": "4",
                  "freeTier1Skills": "0",
                  "fullName": "Ahnika Hartzell",
                  "id": 29,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/06/21",
                  "numEventsAttended": "1",
                  "numNpcEventsAttended": "1",
                  "prestigePoints": "1",
                  "startDate": "2025/06/02",
                  "username": "ahartzell451@gmail.com"
                },
                {
                  "experience": "2",
                  "freeTier1Skills": "0",
                  "fullName": "Willow Jane Yohn ",
                  "id": 30,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "1",
                  "numNpcEventsAttended": "1",
                  "prestigePoints": "0",
                  "startDate": "2025/08/12",
                  "username": "willowyohn@gmail.com"
                },
                {
                  "experience": "6",
                  "freeTier1Skills": "1",
                  "fullName": "Emily Alligood",
                  "id": 31,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "1",
                  "numNpcEventsAttended": "1",
                  "prestigePoints": "0",
                  "startDate": "2025/08/17",
                  "username": "emilyalligood@gmail.com"
                },
                {
                  "experience": "2",
                  "freeTier1Skills": "0",
                  "fullName": "Laura Hagen ",
                  "id": 32,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "1",
                  "numNpcEventsAttended": "1",
                  "prestigePoints": "0",
                  "startDate": "2025/08/19",
                  "username": "hagenjlaura@gmail.com"
                },
                {
                  "experience": "2",
                  "freeTier1Skills": "0",
                  "fullName": "Miles Daniels",
                  "id": 33,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "1",
                  "numNpcEventsAttended": "1",
                  "prestigePoints": "0",
                  "startDate": "2025/08/21",
                  "username": "darkstrike637@gmail.com"
                },
                {
                  "experience": "3",
                  "freeTier1Skills": "1",
                  "fullName": "Alexander Robinson",
                  "id": 34,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "",
                  "numEventsAttended": "0",
                  "numNpcEventsAttended": "0",
                  "prestigePoints": "0",
                  "startDate": "2025/08/22",
                  "username": "alex.robinson@wisc.edu"
                },
                {
                  "experience": "2",
                  "freeTier1Skills": "0",
                  "fullName": "Marcus mack",
                  "id": 35,
                  "isAdmin": "FALSE",
                  "isCheckedIn": "FALSE",
                  "isCheckedInAsNpc": "FALSE",
                  "lastCheckIn": "2025/08/24",
                  "numEventsAttended": "1",
                  "numNpcEventsAttended": "1",
                  "prestigePoints": "0",
                  "startDate": "2025/08/23",
                  "username": "kaimack2017@gmail.com"
                }
              ]
            }
        """

    }
}